#include "extract_pipeline.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <sys/types.h>
#include <yaml.h>
#include <errno.h>
#include <math.h>

#include "pipeline_config.pb-c.h"
#include "module_config.pb-c.h"
#include "metadata.pb-c.h"

int pipeline_initialize_parser(const char *filename, yaml_parser_t *parser, FILE *fh)
{
    fh = fopen(filename, "r");

    /* Initialize parser */
    if (!yaml_parser_initialize(parser))
    {
        fprintf(stderr, "Error: Failed to initialize parser!\n");
        return -1;
    }
    if (fh == NULL)
    {
        fprintf(stderr, "Error: Failed to open file!\n");
        return -1;
    }

    /* Set input file */
    yaml_parser_set_input_file(parser, fh);

    return 0;
}

void pipeline_cleanup_resources(yaml_parser_t *parser, yaml_event_t *event, FILE *fh)
{
    if (event != NULL)
    {
        yaml_event_delete(event);
    }
    yaml_parser_delete(parser);

    if (fh != NULL)
    {
        fclose(fh);
    }
}

/* Renamed enum to avoid collisions */
enum pipeline_state
{
    STATE_START,    /* start state */
    STATE_STREAM,   /* start/end stream */
    STATE_DOCUMENT, /* start/end document */
    STATE_SECTION,  /* top level */

    STATE_MLIST,   /* module list */
    STATE_MVALUES, /* module key-value pairs */
    STATE_MKEY,    /* module key */
    STATE_MNAME,   /* module name value */

    STATE_ILIST,    /* implementations list */
    STATE_IVALUES,  /* implementation key-value pairs */
    STATE_IKEY,     /* implementation key */
    STATE_IPARAMID, /* implementation param_id */
    STATE_IEFFORT,  /* implementation effort */

    STATE_STOP /* end state */
};

/* Renamed struct to avoid collisions */
struct pipeline_parser_state
{
    enum pipeline_state state;      /* The current parse state */
    struct ModuleDefinition m;      /* Module data elements. */
    struct Implementation i;        /* Implementation data elements. */
    struct Implementation *ilist;   /* List of 'implementation' objects. */
    size_t n_implementations;       /* Number of implementations in list. */
    struct ModuleDefinition *mlist; /* List of 'module' objects. */
    size_t n_modules;               /* Number of modules in list. */
};

/*
 * Consume yaml events generated by the libyaml parser to
 * import our data into raw c data structures. Error processing
 * is keep to a mimimum since this is just an example.
 */
/* signature updated to use pipeline_parser_state */
int pipeline_consume_event(struct pipeline_parser_state *s, yaml_event_t *event)
{
    char *value;

    switch (s->state)
    {
    case STATE_START:
        switch (event->type)
        {
        case YAML_STREAM_START_EVENT:
            s->state = STATE_STREAM;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_STREAM:
        switch (event->type)
        {
        case YAML_DOCUMENT_START_EVENT:
            s->state = STATE_DOCUMENT;
            break;
        case YAML_STREAM_END_EVENT:
            s->state = STATE_STOP; /* All done. */
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_DOCUMENT:
        switch (event->type)
        {
        case YAML_MAPPING_START_EVENT:
            s->state = STATE_SECTION;
            break;
        case YAML_DOCUMENT_END_EVENT:
            s->state = STATE_STREAM;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_SECTION:
        switch (event->type)
        {
        case YAML_SCALAR_EVENT:
            value = (char *)event->data.scalar.value;
            if (strcmp(value, "pipeline") == 0)
            {
                s->state = STATE_MLIST;
            }
            else
            {
                fprintf(stderr, "Unexpected scalar: %s\n", value);
                return -1;
            }
            break;
        case YAML_DOCUMENT_END_EVENT:
            s->state = STATE_STREAM;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_MLIST:
        switch (event->type)
        {
        case YAML_SEQUENCE_START_EVENT:
            s->state = STATE_MVALUES;
            break;
        case YAML_MAPPING_END_EVENT:
            s->state = STATE_SECTION;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_MVALUES:
        switch (event->type)
        {
        case YAML_MAPPING_START_EVENT:
            s->state = STATE_MKEY;
            break;
        case YAML_SEQUENCE_END_EVENT:
            s->state = STATE_MLIST;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_MKEY:
        switch (event->type)
        {
        case YAML_SCALAR_EVENT:
            value = (char *)event->data.scalar.value;
            if (strcmp(value, "name") == 0)
            {
                s->state = STATE_MNAME;
            }
            else if (strcmp(value, "implementations") == 0)
            {
                s->state = STATE_ILIST;
            }
            else
            {
                fprintf(stderr, "Unexpected key: %s\n", value);
                return -1;
            }
            break;
        case YAML_MAPPING_END_EVENT:
            // printf("Completed module: %s with %zu implementations\n", s->m.name, s->n_implementations);
            // allocate new module in list
            ModuleDefinition *temp = realloc(s->mlist, ++(s->n_modules) * sizeof(ModuleDefinition));
            if (!(temp))
            {
                fprintf(stderr, "Error: Failed to allocate memory for ModuleDefinition during parsing\n");
                return -1;
            }
            s->mlist = temp;
            // push the current module onto the list
            s->m.n_implementations = s->n_implementations;
            s->m.implementations = malloc(s->n_implementations * sizeof(Implementation *));
            for (size_t i = 0; i < s->n_implementations; i++)
            {
                s->m.implementations[i] = &(s->ilist[i]);
            }
            s->mlist[s->n_modules - 1] = s->m;
            // reset current module
            ModuleDefinition module = MODULE_DEFINITION__INIT;
            s->m = module;
            Implementation implementation = IMPLEMENTATION__INIT;
            s->i = implementation;
            s->n_implementations = 0;
            s->ilist = NULL;
            s->state = STATE_MVALUES;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_MNAME:
        switch (event->type)
        {
        case YAML_SCALAR_EVENT:
            s->m.name = strdup((char *)event->data.scalar.value);
            s->state = STATE_MKEY;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_ILIST:
        switch (event->type)
        {
        case YAML_SEQUENCE_START_EVENT:
            s->state = STATE_IVALUES;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_IVALUES:
        switch (event->type)
        {
        case YAML_MAPPING_START_EVENT:
            s->state = STATE_IKEY;
            break;
        case YAML_SEQUENCE_END_EVENT:
            s->state = STATE_MKEY;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_IKEY:
        switch (event->type)
        {
        case YAML_SCALAR_EVENT:
            value = (char *)event->data.scalar.value;
            if (strcmp(value, "param_id") == 0)
            {
                s->state = STATE_IPARAMID;
            }
            else if (strcmp(value, "effort_level") == 0)
            {
                s->state = STATE_IEFFORT;
            }
            else
            {
                fprintf(stderr, "Unexpected key: %s\n", value);
                return -1;
            }
            break;
        case YAML_MAPPING_END_EVENT:
            // printf("  Completed implementation: param_id=%d effort_level=%d\n",
            //        s->i.param_id,
            //        s->i.effort_level);
            // allocate new implementation in list
            Implementation *temp = realloc(s->ilist, ++(s->n_implementations) * sizeof(Implementation));
            if (!(temp))
            {
                fprintf(stderr, "Error: Failed to allocate memory for Implementation during parsing\n");
                return -1;
            }
            s->ilist = temp;
            // push the current implementation onto the list
            s->ilist[s->n_implementations - 1] = s->i;
            Implementation implementation = IMPLEMENTATION__INIT;
            s->i = implementation;
            s->state = STATE_IVALUES;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_IPARAMID:
        switch (event->type)
        {
        case YAML_SCALAR_EVENT:
            if (s->i.param_id)
            {
                fprintf(stderr, "Warning: duplicate 'param_id' key.\n");
                s->i.param_id = 0;
            }
            s->i.param_id = atoi((char *)event->data.scalar.value);
            s->state = STATE_IKEY;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_IEFFORT:
        switch (event->type)
        {
        case YAML_SCALAR_EVENT:
            if (strcmp((char *)event->data.scalar.value, "low") == 0)
            {
                s->i.effort_level = EFFORT_LEVEL__LOW;
            }
            else if (strcmp((char *)event->data.scalar.value, "medium") == 0)
            {
                s->i.effort_level = EFFORT_LEVEL__MEDIUM;
            }
            else if (strcmp((char *)event->data.scalar.value, "high") == 0)
            {
                s->i.effort_level = EFFORT_LEVEL__HIGH;
            }
            else if (strcmp((char *)event->data.scalar.value, "default") == 0)
            {
                s->i.effort_level = EFFORT_LEVEL__DEFAULT;
            }
            else
            {
                fprintf(stderr, "Unexpected effort level: %s\n", (char *)event->data.scalar.value);
                return -1;
            }
            s->state = STATE_IKEY;
            break;
        default:
            fprintf(stderr, "Unexpected event %d in state %d.\n", event->type, s->state);
            return -1;
        }
        break;

    case STATE_STOP:
        break;
    }
    return 0;
}

/* Parse a YAML file and populate a PipelineDefinition structure.
   Returns 0 on success, -1 on failure. The returned PipelineDefinition
   will reference ModuleDefinition objects allocated internally; caller
   should ensure lifetime until packing or copying. */
int parse_pipeline_yaml_file(const char *filename, PipelineDefinition *pipeline)
{
    yaml_parser_t parser;
    FILE *fh = NULL;
    if (pipeline_initialize_parser(filename, &parser, fh) < 0)
        return -1;

    struct pipeline_parser_state state; // updated type here
    memset(&state, 0, sizeof(state));
    state.state = STATE_START;

    int status = 0;

    do
    {
        yaml_event_t event;

        status = yaml_parser_parse(&parser, &event);
        if (status < 0)
        {
            fprintf(stderr, "Error: Parser error %d\n", parser.error);
            return -1;
        }
        status = pipeline_consume_event(&state, &event); // updated call
        yaml_event_delete(&event);
        if (status < 0)
        {
            fprintf(stderr, "Error: Failed to consume event\n");
            return -1;
        }
    } while (state.state != STATE_STOP);

    printf("Parsed %zu modules in pipeline.\n", state.n_modules);

    pipeline_cleanup_resources(&parser, NULL, fh);

    pipeline->n_modules = state.n_modules;
    for (size_t i = 0; i < state.n_modules; i++)
    {
        pipeline->modules = realloc(pipeline->modules, (i + 1) * sizeof(ModuleDefinition *));
        pipeline->modules[i] = &state.mlist[i];
    }

    return 0;
}